/*
 * Copyright (C) 2014 CEAACES
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package ec.gob.ceaaces.datastore;

import ec.gob.ceaaces.datastore.exception.DataStoreAlreadyExistsException;
import ec.gob.ceaaces.datastore.exception.DataStoreException;
import java.io.InputStream;

/**
 * The interface allow to relize the following:
 * <br>
 * <ul>
 * <li>Upload file from InputStream</li>
 * <li>Upload file from byte array</li>
 * <li>Download file from id repository</li>
 * <li>Download file from absoluty path</li>
 * </ul>
 *
 * @author CEAACES
 * @version 1.0
 */
public interface DataStore {

    /**
     * Method that allow upload a file.
     *
     * @param relativePath Relative path where it will be saved the file.
     * @param nameFile Name file
     * @param inputStream Object with input stream
     * @return ID is generated by the server for identify the file.
     * @throws DataStoreException is thrown in the follow case:
     * <br>
     * <ul>
     * <li>When fail the conection with the server.</li>
     * </ul>
     * @throws ec.gob.ceaaces.datastore.exception.DataStoreAlreadyExistsException
     */
    String uploadFile(String relativePath, String nameFile, InputStream inputStream) throws DataStoreException, DataStoreAlreadyExistsException;

    /**
     * Method that allow upload a file from a byte array.
     *
     * @param relativePath Relative path where it will be saved the file.
     * @param fileName Name of the file.
     * @param arrayFile array of the byte that it contains the information of
     * the file.
     * @return ID is generated by the server for identify the file.
     * @throws DataStoreException is thrown in the follow case:
     * <br>
     * <ul>
     * <li>When fail the conection with the server.</li>
     * </ul>
     * @throws ec.gob.ceaaces.datastore.exception.DataStoreAlreadyExistsException
     */
    String uploadFile(String relativePath, String fileName, byte[] arrayFile) throws DataStoreException, DataStoreAlreadyExistsException;

    /**
     * Method that allow download a file from absotule path like parameter.
     * @param absolutePath It's the path where it found the file.
     * @return Instance of InputStream 
     * @throws DataStoreException is thrown when the file is not found.
     */
    InputStream downloadFileByPath(String absolutePath) throws DataStoreException;

    /**
     * Method that allow download a file from id.
     * @param id It's the identification of the file, the same is given for the server when you upload the file.
     * @return Instance of InputStream.
     * @throws DataStoreException is thrown when the file is not found.
     */
    InputStream downloadFileById(String id) throws DataStoreException;
    
    /**
     * 
     * @param absolutePath
     * @throws DataStoreException 
     */
    void createPath(String absolutePath) throws DataStoreException;
}
